### ISSUE TITLE
Need support

### ISSUE THREAD

**Issue by XavierQL** [powei-lin/aprilgrid#2]
Much appreciation for your sharing this coding. it's useful. 
Here i am looking forward for your help
1. As you see the orignal pic, all the apriltags can be checked using pupli_apritags. but aprilgrid can't ,even using the undistored pic.(see the below pic.). meanwhile, very curiously, as your demo shown, the aprilgride board for calibration can be detected well by your code, inversely, pupil_apriltags failed everytime expect the example i show here. So can you help me to anaysize what's reason? meanwhile, in the last pic, this is generated by kablir: tagsize:5m, and ratio is 0.25，it‘s not detected by aprilgrid, can you help debug this?
orignal: ![new2](https://github.com/powei-lin/aprilgrid/assets/140784183/8c8ed1ab-153c-4f83-8d1c-e8ff7b71cac2)
pupil_apriltags check result: ![test](https://github.com/powei-lin/aprilgrid/assets/140784183/7c8c8fbe-5d34-4261-af7e-ee9c24b83abb)
aprilgrid check using undistorted pic : ![test](https://github.com/powei-lin/aprilgrid/assets/140784183/c40b744e-3a76-4bf1-8567-f814f2c44b18)
aprilgrid coding can't detect this pic: ![HD](https://github.com/powei-lin/aprilgrid/assets/140784183/10d6cb1f-3ae1-423c-b455-22abce62c4b4)

**Comment by powei-lin** [comment]
Because aprilgrid follows kalibr and uses 2bit black as the margin for each marker. Whereas apriltag3 uses 1bit black as the margin.

**Comment by powei-lin** [comment]
![img](https://github.com/powei-lin/aprilgrid/assets/14972130/05aceb72-51c9-4120-9fdd-00a228ea0a08)
![img2](https://github.com/powei-lin/aprilgrid/assets/14972130/018de3d0-1d1d-4af5-ae79-033477ee0b08)
I added the support for 1-bit black border tags. Please upgrade aprilgrid to 0.3.0 and try with
`detector = Detector('t36h11b1')`.

I tested detecting your image using a fisheye camera and it worked.

**Comment by powei-lin** [comment]
Feel free to let me know if you need any help.

**Comment by XavierQL** [comment]
Much appreciated for your feedback. I have trial on ver.0.3.0, it works.  
From my trial run, I found some phenomna：
1. As your seen, there is degradation at the below image.
![image](https://github.com/powei-lin/aprilgrid/assets/140784183/4b30a137-d27f-4b15-ba3a-412555ae50ef)
2. the apriltag detection is sensitive with the orignal resolution of image. I noticed the image scaling in your code. I am confused by pupil-apriltags code detection result which is extremely not stable. but your code is very stable. 
**Can you share me with the keypoint?**
Should we chat by skype for convenience？：https://join.skype.com/invite/u1M14SpZ2On7

**Comment by powei-lin** [comment]
The Python version is not exactly the same as the original version. The tag needs to be detected and then decoded, but one bit black makes the tag harder to detect as a square I guess. Since your original issue is solved I'll close this issue. I'm not comfortable using Skype to chat so sorry for that.
If you can help improve the detection I'm very welcome to any pull request! thanks!

**Comment by XavierQL** [comment]
OK，thanks a lot
