### ISSUE TITLE
World Coordiantes

### ISSUE THREAD

**Issue by Yonghao-Tan** [powei-lin/aprilgrid#3]
How can I generate the world coordinates of the aprilgrid? Thanks

**Comment by powei-lin** [comment]
This depends on how you generate the Aprilgrid chart. Each chart has its world coordinates. Also, it depends on your usage. For example, if you're using it for camera intrinsic calibration, the scale probably doesn't matter. But if you need Aprilgrid for making some SLAM/VIO/AR/VR applications, the scale matters.
