### ISSUE TITLE
Problem during usage

### ISSUE THREAD

**Issue by Irrelev4nt13** [powei-lin/aprilgrid#4]
Hello,

I recently cloned your repository and was looking for the program used in the demonstration (GIF), but I couldn't find it. Am I overlooking something, or do I need to create the program manually?

By the way, I'm particularly interested in live tracking of the AprilGrid and the extraction of the pose of the grid at every time. Your repository seems perfect for my needs, but I'm stuck at this point in the process. Any assistance would be greatly appreciated!

**Comment by powei-lin** [comment]
Check out the example code. https://github.com/powei-lin/aprilgrid/blob/main/example/main.py

To extract camera pose, you also need camera intrinsic values and the physical size of the aprilgrid board. And just use opencv solvepnp should be fine.

**Comment by Irrelev4nt13** [comment]
I was experimenting with this file but it was only for images. Is there any easy modification I should do in order for it to be able to live-detect the aprilgrid ?

**Comment by powei-lin** [comment]
Read this https://docs.opencv.org/4.x/dd/d43/tutorial_py_video_display.html
